### PR TITLE
BR-42 Upgrade Maven version

### PR DESCRIPTION
**Pull request by TonyMorrison**
### What does PR do?
Upgraded the Maven version used in the pipeline to 'maven-latest' and upgraded the version of the maven-release-plugin in the pom

### Testing
Tested here in Jenkins
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/DDF-Registry_TM/job/master/

### Reviewers
@shaundmorris 
@LinkMJB 
@bdeining

### CODE REVIEW

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Review by shaundmorris — APPROVED** [review]
@TonyMorrison can you please change this job to also run on change?

**Review by LinkMJB — CHANGES_REQUESTED** [review]
Not to muddy this up too much more, but it would probably be a good idea to enable PR builds in the Jenkinsfile while we are at it

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Review by LinkMJB — APPROVED** [review]

**Pull request merged**
