### PR TITLE
Updates the DDF version to 2.25.2-SNAPSHOT and adds the registry UI

### PR DESCRIPTION
**Pull request by blen-desta**
- Updates the DDF version to 2.25.2-SNAPSHOT
- Adds the registry UI module

### CODE REVIEW

**Review by emmberk — APPROVED** [review]

**Comment by emmberk** [comment]
@blen-desta, @garrettfreibott, and I successfully tested the registry on a downstream project

build now

**Review by parret — APPROVED** [review]

**Comment by emmberk** [comment]
```
15:11:40  2020-08-19T22:10:57,529 | WARN  | vator-1-thread-2 | AetherBasedResolver              | mvn.internal.AetherBasedResolver  807 | 8 - org.ops4j.pax.url.mvn - 2.6.1 | Error resolving artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT: [Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in sonatype-snapshot (https://oss.sonatype.org/content/repositories/snapshots/), Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in ops4j-snapshot (https://oss.sonatype.org/content/repositories/ops4j-snapshots/), Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in apache (https://repository.apache.org/content/groups/snapshots-group/)]
15:11:40  java.io.IOException: Error resolving artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT: [Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in sonatype-snapshot (https://oss.sonatype.org/content/repositories/snapshots/), Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in ops4j-snapshot (https://oss.sonatype.org/content/repositories/ops4j-snapshots/), Could not find artifact ddf.test.itests:test-itests-dependencies-app:xml:features:2.25.2-SNAPSHOT in apache (https://repository.apache.org/content/groups/snapshots-group/)]
```

**Review by bakejeyner — APPROVED** [review]

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Pull request merged**
